spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/country_calling_codes_db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false