client:
  wiki-api:
    url: http://localhost:7071

spring:
  sql:
    init:
      platform: h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=LEGACY;
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        use_sql_comments: false
  h2:
    console:
      enabled: false